### ISSUE TITLE
Update UA's data to replace with github.com/corpix/uarand

### ISSUE THREAD

**Issue by ehsandeep** [projectdiscovery/useragent#102]
Recently we added new [workflow](https://github.com/projectdiscovery/useragent/blob/main/.github/workflows/download-useragents.yml) that periodically update latest browsers UA's using `whatismybrowser.com` paid api to 5 json file named after browser name and `all.txt` that contains all UA's.

```bash
tree user-agents/
user-agents/
├── all.txt
├── chrome.json
├── edge.json
├── firefox-esr.json
├── firefox.json
└── safari.json

0 directories, 6 files
```

Either we can update the workflow or update `cmd/update-useragent/main.go` to make use of new api to update `useragent_data.go` and `useragent_data.json` file in a way that `projectdiscovery/useragent` can be used as drop in replacement of `github.com/corpix/uarand` in all the PD projects.

**Comment by Mzack9999** [comment]
I think this is not allowed by ToS (ref: https://github.com/projectdiscovery/useragent/issues/9#issuecomment-1644066332 and [API](https://developers.whatismybrowser.com/api/about/legal/) at section `6.6.4 - Limitation of use of the database`)

**Comment by ehsandeep** [comment]
> whatismybrowser

I see, sent an email to them asking if it's okay to use this way, we can wait for response before proceeding on this.

**Comment by ehsandeep** [comment]
> I think this is not allowed by ToS (ref: [#9 (comment)](https://github.com/projectdiscovery/useragent/issues/9#issuecomment-1644066332) and [API](https://developers.whatismybrowser.com/api/about/legal/) at section `6.6.4 - Limitation of use of the database`)

I see, sent an email to them asking if it's okay to use this way, we can wait for response before proceeding on this.
