### ISSUE TITLE
Possible incorrect `computer` tag for `mobile` user-agent

### ISSUE THREAD

**Issue by xjasonlyu** [projectdiscovery/useragent#192]
### useragent version:

- `v0.0.71`
### Current Behavior:

```json
  {
    "Tags":[
      "Safari 17.4 on macOS",
      "\u003cnil\u003e",
      "Safari 17.4",
      "Safari",
      "safari",
      "17.4",
      "17.4.1",
      "macOS",
      "macos",
      "browser",
      "web-browser",
      "computer",
      "WebKit"
    ],
    "Raw":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/17.4.1 Mobile/15E148 Safari/604.1"
  },
```

As we can see this UA contains a `Mobile` keyword, but there is no `mobile` in the Tags field. And perhaps should remove the `computer` tag as it's not a Desktop user-agent?

### Expected Behavior:

With at least `mobile` tag included and `computer` tag removed. (?)

### Steps To Reproduce:

Check in the JSON data.

**Comment by dogancanbakir** [comment]
Closing this. Reason: https://github.com/projectdiscovery/useragent/issues/191#issuecomment-2382645737
