### ISSUE TITLE
Add new source & category

### ISSUE THREAD

**Issue by tarunKoyalwar** [projectdiscovery/useragent#9]
# Description

```[tasklist]
- [ ] Add [whatismybrowser.com](https://developers.whatismybrowser.com/useragents/explore/) as source
     - [ ]  Scrape User Agents based on their categories
     - [ ] Add relevant categories 
- [ ]  Add `-latest` flag to fetch latest User Agents.
- [ ]  Add common/popular flags ( -chrome etc )
- [ ] Add using as library example / build test
```

UserAgent data on `whatismybrowser.com` is most recent & structured implementing this will prevent bad data

**Comment by brenocss** [comment]
chrome-legacy
chrome-latest
chrome-mobile
firefox-legacy
...

**Comment by Mzack9999** [comment]
Closing as not planned - Unfortunately I think this is not allowed (Ref: https://developers.whatismybrowser.com/useragents/database/legal/)
